### ISSUE TITLE
Google Sign-In API Non-functioning

### ISSUE THREAD

**Issue by Cahzuhe** [mr-glt/OpenScout#3]
Unable to sign-in to the app using Google.

Phone: Nexus 6P
Android Version: Nougat 7.1.2
Version: Google Play

**Comment by mr-glt** [comment]
I need a logcat from the device.

**Comment by mr-glt** [comment]
It might be related the keystore in firebase

**Comment by mr-glt** [comment]
@Cahzuhe I updated the **keystore** in 513404d. Try [this apk](https://github.com/mr-glt/OpenScout/blob/master/app/Demo.apk)

**Comment by Cahzuhe** [comment]
Issue solved with latest Development update.
